import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "GharSevak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Link to the favicon */}
        <link rel="icon" href="/llogo.jpg" />
        {/* You can also specify other formats or sizes */}
        {/* <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" /> */}
      </head>
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <Header />
          <Toaster />
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
